spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  frontend-url: ${FRONTEND_URL}
  admin:
    email: ${ADMIN_DEFAULT_EMAIL}
    password: ${ADMIN_DEFAULT_PASSWORD}
